//! MIME parsing, Unicode-safe sanitization, and look-alike detection for rusty-imap-mcp.
//!
//! Modules: `parse` (MIME + body extraction), `unicode` (scrubbing),
//! `output` (response shapes), `html` (ammonia-based sanitization),
//! `lookalike` (confusables-backed spoofing detection), `error`.

#![deny(missing_docs)]

pub mod error;
pub mod output;
pub mod parse;
pub mod raw_parts;
pub mod threading;
pub mod unicode;

mod html;
mod lookalike;

#[cfg(any(test, feature = "test-util"))]
pub mod testutil;

pub use error::ContentError;
pub use output::{
    AttachmentMeta, Content, ContentMeta, MailingListInfo, SecurityWarning, Untrusted, WarningCode,
    WarningSeverity,
};
pub use parse::parse_message;
pub use raw_parts::{RawPart, walk_attachment_parts};
pub use threading::{ThreadingHeaders, extract_threading_headers};

/// Extract the `Message-ID` header from raw RFC 5322 bytes.
///
/// Thin wrapper around `mail_parser` so tool handlers do not need to
/// depend on `mail_parser` directly just to read one header off a
/// freshly-built message. Returns `None` when the input is not
/// parseable or when no `Message-ID` header is present.
#[must_use]
pub fn extract_message_id(raw: &[u8]) -> Option<String> {
    mail_parser::MessageParser::new()
        .parse(raw)
        .and_then(|m| m.message_id().map(ToString::to_string))
}

/// Compile-time TR39 confusables map, generated by build.rs from
/// `data/confusables.txt`. Consumed by `lookalike::classify_domain`.
#[expect(
    clippy::unicode_not_nfc,
    reason = "generated TR39 MA table preserves source codepoints verbatim"
)]
#[expect(
    clippy::unreadable_literal,
    reason = "phf_codegen emits raw u64 hash seeds"
)]
mod confusables {
    include!(concat!(env!("OUT_DIR"), "/confusables.rs"));
}

#[cfg(test)]
#[expect(clippy::expect_used, reason = "tests may expect on constructed values")]
mod confusables_tests {
    use crate::confusables::CONFUSABLES;

    #[test]
    fn confusables_map_contains_cyrillic_a_to_latin_a() {
        // U+0430 CYRILLIC SMALL LETTER A → "a" (U+0061)
        let target = CONFUSABLES
            .get(&'\u{0430}')
            .expect("cyrillic a should map via TR39");
        assert_eq!(*target, "a");
    }

    #[test]
    fn confusables_map_size_nontrivial() {
        // Sanity: Unicode 16 has > 6000 MA rows.
        assert!(
            CONFUSABLES.len() > 5000,
            "confusables map is suspiciously small: {}",
            CONFUSABLES.len()
        );
    }
}

#[cfg(test)]
#[expect(clippy::expect_used, reason = "tests")]
mod extract_message_id_tests {
    use super::extract_message_id;

    #[test]
    fn extract_returns_message_id_when_header_present() {
        // Kills all three wholesale stubs at extract_message_id (None,
        // Some(""), Some("xyzzy")). A constructed message with a
        // distinctive Message-ID round-trips through mail_parser to
        // a non-empty Some that contains the id substring.
        let raw = b"From: a@example\r\n\
                    Message-ID: <abc-123@example.com>\r\n\
                    \r\n\
                    body";
        let id = extract_message_id(raw).expect("Message-ID must be extracted");
        assert!(
            id.contains("abc-123@example.com"),
            "expected id to contain abc-123@example.com, got {id:?}",
        );
    }
}
